### PR TITLE
Fix PHP code style errors, per PHPCS

### PR DESCRIPTION
**Pull request by paulschreiber**
Fixes whitespaces error and adds strict equality checks.

`phpcs -p -s -v --colors --standard=WordPress-VIP documentcloud.php`

### CODE REVIEW

**Comment by reefdog** [comment]
@paulschreiber Good idea, running this through phpcs. @bcampeau is currently helping us get approved for WordPress VIP (#30), and I just merged in some requested feedback from the VIP team (#41), which conflicts with your 2adb1e0. Can you resolve and resubmit? And while doing so, can you separate the TinyMCE work into a separate PR? I'd like to evalulate them separately. Thanks!

**Comment by bcampeau** [comment]
I'd like to proceed with the existing VIP review as-is and then push this as the next version, if that's OK.

**Comment by reefdog** [comment]
@bcampeau I think that's sensible, considering the VIP team is already mid-review. On that note, how *do* they handle future releases? Do they evaluate each one?

**Comment by bcampeau** [comment]
Any time you want to push a new version to VIP, you have to open a ticket and request a review.

**Comment by paulschreiber** [comment]
I'll close this PR and make a new PHPCS-only PR.

**Pull request closed without merging**
