### PR TITLE
Canonizing the plugin name

### PR DESCRIPTION
**Pull request by reefdog**
* Rename "Navis DocumentCloud" to "DocumentCloud"
* Change class to `WP_DocumentCloud`
* Remove "navis" references in filenames/paths (including one backwards-incompatible change to the `tinywindow.js` reference)

### CODE REVIEW

**Comment by knowtheory** [comment]
lgtm :+1:

**Comment by knowtheory** [comment]
Feel bad that i just went ahead and merged w/o consulting @eyeseast & @aschweigert, so this is late, but everybody cool w/ the direction this is heading?

We're happy to rework the pieces in here if necessary, most the changes are simply canonicalizing the name and changing some urls & the like.  Chris, in particular is the way we're going about updating the copyright & attribution cool with you?  (essentially just appending our copyright for the things we're updating going forward)

**Comment by eyeseast** [comment]
Wow, there is a ton of work being done all of a sudden. Happy to see it. I'm on the road right now but will dig through this when I have some time.

**Comment by knowtheory** [comment]
We have a team!  And plans!  and we're making progress! :D

Since we're iterating on the oembed endpoint we wanted a test consumer and figured we may as well build one that'll get used by others :)

**Pull request merged**
